# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-12-08 14:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='姓名')),
                ('cause', models.CharField(max_length=64, verbose_name='请假原因')),
                ('start_time', models.DateField(help_text='格式yyyy-mm-dd', verbose_name='请假开始时间')),
                ('end_time', models.DateField(help_text='格式yyyy-mm-dd', verbose_name='请假结束时间')),
                ('case', models.CharField(choices=[('yes', '通过'), ('not', '未通过')], default='not', max_length=16, verbose_name='是否通过')),
            ],
        ),
    ]
