# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-12-09 05:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='case',
            field=models.CharField(choices=[(1, '通过'), (0, '未通过')], default='not', max_length=16, verbose_name='是否通过'),
        ),
    ]
